services:
  django:
    build: ./django
    container_name: tcd_django
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- python manage.py runserver 0.0.0.0:8000  # for development
    # command: daphne -b 0.0.0.0 -p 8000 core.asgi:application # for production
    volumes:
      - ./django:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      default_network:
        aliases:
          - web


  db:
    image: postgres:latest
    container_name: tcd_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tcd_database
    env_file:
      - .env
    networks:
      default_network:
        aliases:
          - db
    healthcheck:
      test: pg_isready -U root -d tcd_database
      interval: 5s
      timeout: 3s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: tcd_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
      - "4430:443"
    depends_on:
      - django
    networks:
      default_network:
        aliases:
          - nginx


volumes:
  postgres_data:


networks:
  default_network:
