services:
  django:
    build: ./django
    container_name: tcd_django
    command: daphne -b 0.0.0.0 -p 8000 core.asgi:application
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      default_network:
        aliases:
          - web
    volumes:
      - static_files:/app/static_files

  db:
    image: postgres:latest
    container_name: tcd_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      DB_NAME: tcd_database
    env_file:
      - .env
    networks:
      default_network:
        aliases:
          - db
    healthcheck:
      test: pg_isready -U $${DB_USER} -d $${DB_NAME}
      interval: 5s
      timeout: 3s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: tcd_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_files:/var/www/html/static
    ports:
      - "8000:80"
    depends_on:
      - django
    networks:
      default_network:
        aliases:
          - nginx


volumes:
  postgres_data:
  static_files:


networks:
  default_network:
