services:
  django:
    build: ./django
    container_name: tcd_django
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      default_network:
        aliases:
          - web
    volumes:
      - static_files:/app/staticfiles
      - media_files:/app/media

  db:
    image: postgres:latest
    container_name: tcd_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tcd_database
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "5433:5432"
    networks:
      default_network:
        aliases:
          - db
    healthcheck:
      test: pg_isready -U $${DB_USER} -d $${DB_NAME}
      interval: 5s
      timeout: 3s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: tcd_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_files:/var/www/html/static
      - media_files:/var/www/html/media
      - cert:/cert
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
      - cert
    networks:
      default_network:
        aliases:
          - nginx

  cert:
    build:
      context: ./openssl-cert
      dockerfile: Dockerfile
    container_name: tcd_cert
    volumes:
      - cert:/cert

  redis:
    image: redis:latest
    container_name: tcd_redis
    networks:
      default_network:
        aliases:
          - redis


volumes:
  postgres_data:
  static_files:
  media_files:
  cert:

networks:
  default_network:
