[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"
watchPatterns = [
    "requirements.txt",
    "src/**",
    "railway.toml",
    "Dockerfile",
]

[deploy]
runtime = "UNSPECIFIED"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10